apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-manage-operatorgroup
  namespace: mas-max-manage
spec:
  targetNamespaces:
    - mas-max-manage
  upgradeStrategy: Default

